sudo: false
language: python
python:
  - 2.7
cache:
  directories:
  - node_modules

before_install:
  - npm install aglio

script:
  - docker build -t history-tests . -f ./tests/Dockerfile
  - docker-compose -f ./tests/docker-compose.yml up -d mongodb
  - docker-compose -f ./tests/docker-compose.yml run history

services:
  - docker

after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
